### ISSUE TITLE
No path found for Manny! glitch

### ISSUE THREAD

**Issue by Gonkalbell** [tobiaspfaff/grim_mouse#13]
There are some areas where you cannot move to by clicking, but you can still walk to them manually. I noticed this glitch in the following areas:
- The beaver dam and the ledge next to the dam
- The circular hub area in Rubacava near the docks
- Parts of the underwater conveyor belt screen in year 3, as well as the nearby elevator screen

**Comment by tobiaspfaff** [comment]
circular hub in rubacave should work in 0.3.
Need to check the other two.

**Comment by tobiaspfaff** [comment]
I think they all work now. If there's still any issue, please re-open.
