### ISSUE TITLE
At El Marrow

### ISSUE THREAD

**Issue by KaiFrederking** [tobiaspfaff/grim_mouse#14]
When arriving at El Marrow (the "pumping tree" in the petrified forest) after first retrieving the key to the burning beavers, the Bonewaggon just drives through the picture without halting and disappears to the right. No further actions possible, though "F1" still works and game can be saved and loaded.
So far not tried to reproduce. Will post if reproducible.

EDIT: Couldn't easily reproduce the event, but got a different error: When returning with the key, on the central clearing on the way to El Marrow, the Bonewaggon with Manny and Glottis just disappeared after the Audio "I'm not going back to that town" (or something like that).

**Comment by KaiFrederking** [comment]
Next Problem: Game freezes after using extinguisher on second jumping beaver (missed first one).
ResidualVM Status Window repeats "function inventory_save_handler [in file Scripts\bd.lua]" indefinitely

**Comment by Sim209** [comment]
I had the same problem with v.0.2 near the pumping tree... Updating to v.03 resolved my problem!

**Comment by KaiFrederking** [comment]
I am on 0.3.

**Comment by tobiaspfaff** [comment]
Ok, I identified the "function inventory_save_handler" one; fixed in git.

Have not been able to reproduce the other two... 
Do you remember any specifics? I.e. for the second one, did you drive down to the town exit and the wagon disappeared, or where you walking somewhere (in that case, where was the wagon parked?) etc.

**Comment by KaiFrederking** [comment]
Unfortunately "no" to both - reproducibility and remembering specifics.
Also, I overwrote the saves.

**Comment by KaiFrederking** [comment]
OK, now I got it reproduced (the first case, driving through El Marrow).
It's actually rather simple: In the central hub, don't click the exit icon towards El Marrow, but just click on the right side of the screen, like this (works better in full screen mode):
![elm01](https://f.cloud.github.com/assets/6854982/2365366/30160130-a6c0-11e3-9a2b-5d2ccba277cd.jpg)

... then this happens (and the car drives out of the picture)
![elm02](https://f.cloud.github.com/assets/6854982/2365368/48d220b4-a6c0-11e3-96f1-83cea4e57477.jpg)

**Comment by KaiFrederking** [comment]
As for the second one: I was in the car and driving towards the exit (thus the "I ain't going back to town" comment) when the waggon, Manny and Glottis just disappeared.
I couldn't reproduce it though and it only happened once.

**Comment by tobiaspfaff** [comment]
A-ha! Thanks for figuring that out, the tree pump bug is fixed now.
If you ever find out how to reproduce the other bug, open a new report.

**Comment by tobiaspfaff** [comment]
fixed in 0.4
