### ISSUE TITLE
Begining of Year 3 

### ISSUE THREAD

**Issue by Sim209** [tobiaspfaff/grim_mouse#15]
(First, thanks a lot to making this... playing Grim Fandango with mouse is an amazing experience.  Here's my feedback for the begining of year 3:)
- Missing (and not working) Hotspots : 
  -> At the begining of Years 3, there is no Hotspots on the boat.  It occurs on first two screens (outside and inside) untill Glotis grab us in "Machinery Room".  After that, no problems.
-  Unable to grab Chepito:
  Under the sea, i speak to Chepito... In the classic game, after we talk to him, he goes to the right of the screen, and continue to sing along.  At that moment, we can grab his lantern.
  In this version, when i talk to Chepito, he goes already to the right of the screen.  After speaking, he goes further more to the right (singing along)... and goes off the screen, so we are unable to grab the lantern.

(Hope that my english is understandable!)

**Comment by tobiaspfaff** [comment]
First one is fixed in git.

**Comment by tobiaspfaff** [comment]
fixed in 0.4
