### ISSUE TITLE
Year 4, at the Florist: Non-functioning hotspots.

### ISSUE THREAD

**Issue by KaiFrederking** [tobiaspfaff/grim_mouse#25]
The scythe can't be used on the doorbell. Also, the exit icon doesn't make Manny leave the shop. Both work via keyboard controls.
![doorbell](https://f.cloud.github.com/assets/6854982/2361944/98b31144-a637-11e3-9629-3496f5efaa9b.jpg)

**Comment by tobiaspfaff** [comment]
fixed.

**Comment by tobiaspfaff** [comment]
in v0.5
