### ISSUE TITLE
Year 4, Casino: Answers to "Demon Quiz"

### ISSUE THREAD

**Issue by KaiFrederking** [tobiaspfaff/grim_mouse#26]
I'm not sure if I'm missing something here or if it really is a bug:

When the demon asks its questions, the latest number on the board is supposed to be the correct answer. The answers to choose from are always one to four.
(In the image, 3 was the first number to be shown, so it isn't the correct answer).
![casino](https://f.cloud.github.com/assets/6854982/2362201/144079c0-a63b-11e3-850c-a7c7b17140f1.jpg)

**Comment by KaiFrederking** [comment]
P.S.: I finally got passed this by continuing until the correct answer actually was in the 1 to 4 range ... still, I somehow remember that to be less tedious in the original version.

**Comment by tobiaspfaff** [comment]
You can scroll the answers up and down (cursor should become an arrow above/below the answer lines). Does this work? Also, it looks like the bottom part of the screen is cut off, that may be the reason you didn't notice the scrolling option (four should be fully visible). Does that happen for the whole game?

**Comment by KaiFrederking** [comment]
I tried to scroll but it didn't work (or I didn't do it right). I didn't notice any arrows. The cut off screen is an artifact of the screenshot - it looked good on screen.

I'll go back and see if I still have the save.

**Comment by KaiFrederking** [comment]
Oh dear, you are absolutely right: I had missed the arrows.
Workes like a charm :)

**Comment by tobiaspfaff** [comment]
ok, awesome. Maybe I should put some visible arrows there or something, as this is the only place where there are more then 4 options in the dialogue.

**Comment by KaiFrederking** [comment]
One correction: The cut-off is not an artifact, but is actually there in windowed mode, but not in full screen. Even with the bottom lines missing, it is possible to scroll down, but one has to move the cursor to the right - somewhat counter-intuitively. See here:
![casino2](https://f.cloud.github.com/assets/6854982/2362764/0044e28c-a643-11e3-8532-74cbc35edd67.jpg)

**Comment by KaiFrederking** [comment]
... and yes, I agree, permanent arrows instead of mouse-over ones might be good to help hasty people like me :)

**Comment by KaiFrederking** [comment]
Further correction: The "missing bottom lines" only happen when Alt-Entering out of full-screen mode. A game started in windowed mode doesn't have them:
![casino3](https://f.cloud.github.com/assets/6854982/2362874/a97e8fa0-a644-11e3-9e4f-1d07a17b60f7.jpg)

**Comment by tobiaspfaff** [comment]
Ok, I've put nice little arrow there now :)

**Comment by tobiaspfaff** [comment]
in v0.5
