### ISSUE TITLE
Choppy credits

### ISSUE THREAD

**Issue by KaiFrederking** [tobiaspfaff/grim_mouse#27]
Probably nothing to do with the mouse control, but with the VM:
The game end credits just flicker in and out, most of the time the screen is black. Music plays fine. Alt-Enter to reduce full-screen to window immediately terminates the program.

That's my test-and-fun run for now. Incredible job with the mouse control! THANK YOU! How about doing "Alone in the Dark" next? Just kidding :) ... mostly

**Comment by tobiaspfaff** [comment]
fixed

**Comment by tobiaspfaff** [comment]
in v0.5
