### ISSUE TITLE
Inventory not showing up.

### ISSUE THREAD

**Issue by BoatWithLegs** [tobiaspfaff/grim_mouse#32]
Here's a video of my problem. https://www.youtube.com/watch?v=elRPYoHKS2w
This is probably an issue on my end as nobody else has brought it up. I'd still be great if someone could help me troubleshoot.

**Comment by tobiaspfaff** [comment]
yup, that is definitely a regression. Thanks for pointing it out!
It's fixed now and included in v0.5
