### ISSUE TITLE
Cannot exit viewing cat race photo

### ISSUE THREAD

**Issue by tahuomo** [tobiaspfaff/grim_mouse#36]
Mouse mod v0.5_git

If cat race photo is viewed directly from inventory (via left click), the inventory menu lays over the photo. When pressed outside the inventory, inventory closes but the cursor is just big X.There is no way to exit viewing the photo.

Works fine if you first take out the photo from inventory, then look at it (inventory closed) via right click. Can then be exited only via escape button.

**Comment by tobiaspfaff** [comment]
ah, missed that screen. fixed in git now.

**Comment by tobiaspfaff** [comment]
in v0.6
