### ISSUE TITLE
Don't work on mac osx 10.6.8

### ISSUE THREAD

**Issue by Harrypoppins** [tobiaspfaff/grim_mouse#4]
Hello, as the title say there is no way to launch it on osx 10.6.8.

Here is the log :

Here is log :
Process: launchd [754]
Path: /Users/Harry/Desktop/Residual.app/Contents/MacOS/residualvm
Identifier: org.residualvm.residualvm
Version: ??? (???)
Code Type: X86-64 (Native)
Parent Process: launchd [127]

Date/Time: 2014-02-25 18:33:08.839 +0100
OS Version: Mac OS X 10.6.8 (10K549)
Report Version: 6

Interval Since Last Report: 45990628 sec
Crashes Since Last Report: 430
Per-App Crashes Since Last Report: 9
Anonymous UUID: 1FAEA02B-6E28-4673-89A3-EACF0915DC68

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread: Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
rax: 0x0000000000000055 rbx: 0x0000000000000000 rcx: 0x0000000000000000 rdx: 0x0000000000000000
rdi: 0x0000000000000000 rsi: 0x0000000000000000 rbp: 0x0000000000000000 rsp: 0x0000000000000000
r8: 0x0000000000000000 r9: 0x0000000000000000 r10: 0x0000000000000000 r11: 0x0000000000000000
r12: 0x0000000000000000 r13: 0x0000000000000000 r14: 0x0000000000000000 r15: 0x0000000000000000
rip: 0x00007fff5fc01028 rfl: 0x0000000000010203 cr2: 0xfffffffffffffff8

Binary images description not available

Model: MacBookPro6,2, BootROM MBP61.0057.B0C, 2 processors, Intel Core i7, 2.66 GHz, 8 GB, SMC 1.58f16
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 512 MB
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In, 288 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.10.131.42.4)
Bluetooth: Version 2.4.5f3, 2 service, 19 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: ST9500420ASG, 465,76 GB
Serial ATA Device: M4-CT256M4SSD2, 238,47 GB
USB Device: Hub, 0x0424 (SMSC), 0x2514, 0xfd100000 / 2
USB Device: USB Storage, 0x05e3 (Genesys Logic, Inc.), 0x0718, 0xfd130000 / 5
USB Device: Built-in iSight, 0x05ac (Apple Inc.), 0x8507, 0xfd110000 / 4
USB Device: IR Receiver, 0x05ac (Apple Inc.), 0x8242, 0xfd120000 / 3
USB Device: Hub, 0x0424 (SMSC), 0x2514, 0xfa100000 / 2
USB Device: Generic USB Hub, 0x058f (Alcor Micro, Corp.), 0x9254, 0xfa140000 / 6
USB Device: USB Receiver, 0x046d (Logitech Inc.), 0xc52b, 0xfa143000 / 8
USB Device: USB Receiver, 0x046d (Logitech Inc.), 0xc52f, 0xfa141000 / 7
USB Device: Apple Internal Keyboard / Trackpad, 0x05ac (Apple Inc.), 0x0237, 0xfa120000 / 5
USB Device: Internal Memory Card Reader, 0x05ac (Apple Inc.), 0x8403, 0xfa130000 / 4
USB Device: BRCM2070 Hub, 0x0a5c (Broadcom Corp.), 0x4500, 0xfa110000 / 3
USB Device: Bluetooth USB Host Controller, 0x05ac (Apple Inc.), 0x8218, 0xfa113000 / 9

**Comment by tobiaspfaff** [comment]
Ok, I have to admit, I have no clue what happened there. Can you try if plain ResidualVM (newest version from residualvm.org) works on your machine?

**Comment by Harrypoppins** [comment]
Yep it work fine :
https://www.dropbox.com/s/8t77qag70wbvzcn/Capture%20d%27%C3%A9cran%202014-02-27%2018.49.06.png

**Comment by tobiaspfaff** [comment]
Hmm I have the feeling this is more about how I build the binaries than the actual changes in code. If you want, you can try to build grim mouse from source (same way you build residualvm, see their wiki) and see if that works.
Other than that, I have no idea on how to find out what going wrong.

**Comment by tobiaspfaff** [comment]
Ok, different idea: Can you run the debug build
http://graphics.berkeley.edu/~tpfaff/data/grim_mouse_0_3_debug.dmg
and post the stack trace? This might tell me where exactly your version crashes.

**Comment by Harrypoppins** [comment]
Thanks to follow bro, here is the result : 
Process:         launchd [27763]
Path:            /Users/Harry/Desktop/ResidualVM.app/Contents/MacOS/residualvm
Identifier:      org.residualvm.residualvm
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [292]

Date/Time:       2014-03-10 22:57:03.702 +0100
OS Version:      Mac OS X 10.6.8 (10K549)
Report Version:  6

Interval Since Last Report:          46877277 sec
Crashes Since Last Report:           432
Per-App Crashes Since Last Report:   11
Anonymous UUID:                      1FAEA02B-6E28-4673-89A3-EACF0915DC68

Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0xfffffffffffffff8
Crashed Thread:  Unknown

Backtrace not available

Unknown thread crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000055  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x0000000000000000
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff5fc01028  rfl: 0x0000000000010203  cr2: 0xfffffffffffffff8

Binary images description not available

**Comment by Harrypoppins** [comment]
Any idea ?

**Comment by tobiaspfaff** [comment]
Does this still happen with 0.4?

**Comment by Harrypoppins** [comment]
Still not work.
Cheers

**Comment by Harrypoppins** [comment]
Sadly it still don't work.

**Comment by tobiaspfaff** [comment]
Is that with 0.6?

**Comment by Harrypoppins** [comment]
Yeah it work !

CFan you explain how you have fix this ? (For some other open source project)

Many thanks for the support !

**Comment by tobiaspfaff** [comment]
It comes down to compiling and linking everything in your project with -mmacosx-version-min=10.5 (or whatever version you want to support). You can test if that worked by probing your binary with otool -l, and checking for os version.

**Comment by tobiaspfaff** [comment]
This may also include libraries you link against (I had to recompile SDL with this flag).
I'm glad it works now for you!
