### ISSUE TITLE
Beaver Dam bug can't continue 

### ISSUE THREAD

**Issue by TheWrightStuff1994** [tobiaspfaff/grim_mouse#40]
When i go into the level with the beaver dam, a cut scene happens but Manny moves in a different direction and then it shows a movie cut scene where the beaver chomps at the screen and then all of a sudden the beaver go to the top of the screen and then the game locks up and i can't do anything Please help

**Comment by Palalalai** [comment]
I'm having this issue too,

**Comment by tobiaspfaff** [comment]
Is this using v0.6, or did you use an earlier version or load a save game created using an older version? We had a similar bug in earlier versions which was fixed in 0.5.
Also, to keep playing note that you can skip ahead (shift+z to activate devmode, Ctrl+g to jump. fc,re are the scene codes of rubacava, directly after the beaver dam puzzle)

**Comment by TheWrightStuff1994** [comment]
I use v0.6 and it did not work for me please tell me how to add or play Grim with this? because the instructions are very vague on how to play the mod?

**Comment by TheWrightStuff1994** [comment]
Also thanks for the comment to use devmode it help me out!

**Comment by tobiaspfaff** [comment]
I'm confused: So does the issue still occur in v0.6 for you or not ?

**Comment by TheWrightStuff1994** [comment]
Sorry for the confusion. Yes the mod does not (For me) work on v0.6 i try everything to make it work but i just can't for the life of me know how to do it.

**Comment by tobiaspfaff** [comment]
So you can't get v0.6 to work at all (how does this manifest ?) or you encountered the beaver dam bug in v0.6 ?

**Comment by TheWrightStuff1994** [comment]
I can get v0.6 to work but it just Stops at the point on the beaver dam scene. But your suggestion on devtools help me get past the scene.

**Comment by phob** [comment]
This bug occur to me too everytime. The movie plays and after that i can't continue without the workaround with the dev mode. so i don't think this should be closed.

**Comment by tobiaspfaff** [comment]
Yeah, this is definitely a problem. I'll have a look at it. Any idea on how I can reproduce the bug? If I start a new game on v0.6, jump to bv and walk into the door works fine for me. Or if someone could send me a v0.6 savegame from just before that happens, (verticalduck (at) gmail.com), that'd also be helpful.

**Comment by phob** [comment]
Sorry I have overwritten my two saves after I used the devmode. But you can reproduce it I would say everytime with 0.6 by just playing from the beginning. I had a savebug just before this location so I had to restart the game and it took me with skipping all dialogs just about 20 minutes to come to the petrified forrest.

**Comment by TheWrightStuff1994** [comment]
For some reason now it works for me only if I use devmode to go to that scene

**Comment by phob** [comment]
But to use the devmode can't be the goal to this bug so please stop
spamming the issues section.

2014-06-19 1:45 GMT+02:00, dest1234 notifications@github.com:

**Comment by tobiaspfaff** [comment]
I think he meant to reproduce the bug, you have to play the game from beginning, not just jump ahead to the beaver dam, which is useful information for me.

**Comment by TheWrightStuff1994** [comment]
Yes tobiaspfaff that is what i meant about the bug

**Comment by tobiaspfaff** [comment]
found the bug. fixed in v0.7
