### ISSUE TITLE
Dialogs stopped working with version 0.6

### ISSUE THREAD

**Issue by neslib** [tobiaspfaff/grim_mouse#41]
You cannot choose dialog options anymore in version 0.6. Not with the mouse and not with the keyboard. It worked fine in 0.5. Dialog lines also don't highlight yellow anymore when hovering the mouse over them. You can test this in the very first dialog in the game with Eva.

The Status Window adds the following output when selecting a dialog line:

Active Stack:
        'error' tag method at line 2365 [in file Scripts_system.lua]
        function (Scripts_dialog.lua:290)
WARNING: Stub function: Lua_V1::SpewStartup!
lua: unexpected type to index table
Active Stack:
        'error' tag method at line 2371 [in file Scripts_system.lua]
        function (Scripts_dialog.lua:290)

**Comment by tobiaspfaff** [comment]
Ugh, yeah, that's the Android extensions interacting badly with my mouse code. Will fix later tonight.

**Comment by tobiaspfaff** [comment]
Fixed now, and v0.6 binaries updated for mac (will update the windows v0.6 package in the next days, use v0.5 for now).

**Comment by neslib** [comment]
Thanks for fixing this fast!

**Comment by tobiaspfaff** [comment]
Windows v0.6 binary is now updated, too.
Thanks for reporting !
