### ISSUE TITLE
Now v0.7 can't save games

### ISSUE THREAD

**Issue by TheWrightStuff1994** [tobiaspfaff/grim_mouse#42]
I was trying out the new v0.7 with the beaver dam fix and as i was playing Grim i wanted to save so i don't lose track but as i save it stop running and was frozen so i had to use Task Manager it get out (Because i was on fullscreen) so i thought maybe it was the fullscreen that did it so it try it again but windowed mode and it still did not save Please help

**Comment by tobiaspfaff** [comment]
That's a bug from the main ResidualVM repository that I pulled. There's already a fix for it, I'll pull the fix and update the binaries soon.

**Comment by tobiaspfaff** [comment]
Ok, v0.7 is now updated with the savegame fix from the main branch.
