### ISSUE TITLE
I can't load savegames created in grim_mouse 0.4

### ISSUE THREAD

**Issue by marcowy** [tobiaspfaff/grim_mouse#43]
Hello

I can't load any savegame created in grim_mouse 0.4 in higher version (0.5 nor 0.6 nor 0.7).

**Comment by tobiaspfaff** [comment]
Yeah, that's an unfortunately consequence of the way the ResidualVM savegames work. As the whole VM state is saved, older savegames overwrite code changes in the new version, and are therefore incompatible. There's no way I can think of to make this work; sorry. You may consider starting a new game, activating dev. mode (Shift+Z) and jumping ahead (Ctrl+G) using the debug codes http://wiki.residualvm.org/index.php/Grim_Fandango_Debug_Mode

**Comment by marcowy** [comment]
Thanks for the tip. It is also workaround for my main issue with game stuck in Beaver Dam.
(but I used jump target command (key "J") instead of jump to set (Ctrl+G))

**Comment by marcowy** [comment]
I've upgraded grim_mouse to 0.7, used ctrl+G to beaver dam (bd) and save the game.
And I can't load that savegame. Tried few times - black screen appear for few seconds than game immediately quit without any error nor message.

**Comment by marcowy** [comment]
Hmm tried one more time and now it works...

**Comment by marcowy** [comment]
...and it doesn't solve my problem, because there is no Glottis in front of the gate to beaver dam when I use ctrl+g code.

**Comment by tobiaspfaff** [comment]
Well, the jump to scene codes are a hack, obviously. If you jump directly to "bv", Glottis still doesn't have its heart (even if he appears in the cut scene), so you'd have to redo this part. What generally works well though is to jump to the beginning of a chapter, so in your case either "sm" for the petrified forest or "re" for Rubacava.
I know it's annoying that savegames are incompatible, but there's not much I can do about it.

**Comment by marcowy** [comment]
There is one more problem with jump hack - the puzzle which is visible in save/load menu doesn't reflect current progress. But I assume it not affects game itself. However I've started game from beginning with grim_mouse 0.7.
