### ISSUE TITLE
Beaver dam - game not respond to any key nor mouse clicks

### ISSUE THREAD

**Issue by marcowy** [tobiaspfaff/grim_mouse#44]
Grim_mouse 0.4.

Cursor has cross-form (see attached screenshot), I can move it but game doesn't respond to any clicks, nor key controls (except F1, alt+Enter etc.).

![beaver dam stuck](https://cloud.githubusercontent.com/assets/7999161/3403564/905c4dd0-fd67-11e3-8039-8d4b5db1ef0f.jpg)

**Comment by tobiaspfaff** [comment]
Yeah, that's issue 40 
https://github.com/tobiaspfaff/grim_mouse/issues/40

It's fixed in v0.7

**Comment by marcowy** [comment]
I can't open savegame from 0.4 which in I was playing. But thanks to your tip about devmode and jump in issue https://github.com/tobiaspfaff/grim_mouse/issues/43 I am able to continue playing from that scene.

Thanks for ultra-rapid answer! :)
