### ISSUE TITLE
SDL.dll missing

### ISSUE THREAD

**Issue by trlkly** [tobiaspfaff/grim_mouse#45]
It seems that you did not include a required DLL in your package. Either you need to, or the instructions need to be updated to include how to get said DLL.

**Comment by tobiaspfaff** [comment]
True. The file is included now.

**Comment by trlkly** [comment]
Rather than post another bug, I'll point out that you might want to mention SDL.dll in your installation instructions [here](http://tobiaspfaff.com/blog/2014/05/25/grim/) Right now it just says to copy residualvm.exe and mouse.lab.

**Comment by tobiaspfaff** [comment]
Yeah, I should changes that too. Thanks for the hint!
