### ISSUE TITLE
screen without hotspots

### ISSUE THREAD

**Issue by nadegr** [tobiaspfaff/grim_mouse#5]
in year 1 there is a screen without hotspots.
![screen shot 2014-02-26 at 5 39 22 am](https://f.cloud.github.com/assets/6789829/2266562/71b92012-9e9c-11e3-9d3c-cf8dfa33e0d3.png)
manny can look at the red tube and the machine from that screen using only the keyboard.

after you mess the machine up some hotspots work but manny walks to a different screen in order to look at them.
![screen shot 2014-02-26 at 5 47 29 am](https://f.cloud.github.com/assets/6789829/2266575/c18cc5a8-9e9c-11e3-8436-1e5d2d768144.png)

**Comment by tobiaspfaff** [comment]
Interesting. I'll check it out.

**Comment by tobiaspfaff** [comment]
Fixed in git

**Comment by tobiaspfaff** [comment]
Fixed in 0.3
