### ISSUE TITLE
no hotspot for foam

### ISSUE THREAD

**Issue by nadegr** [tobiaspfaff/grim_mouse#6]
in year 1 you can make foam using the two tubes
![screen shot 2014-02-26 at 5 41 18 am](https://f.cloud.github.com/assets/6789829/2266587/1f39af18-9e9d-11e3-9352-320d41558b1f.png)
however you cant select the foam with the mouse, only with the keyboard.
also it doesn't appear when you press space.

**Comment by tobiaspfaff** [comment]
Ok, I forgot an hotspot there. Will fix.

**Comment by tobiaspfaff** [comment]
Fixed in git

**Comment by tobiaspfaff** [comment]
Fixed in 0.3
