### ISSUE TITLE
cant walk through gate

### ISSUE THREAD

**Issue by nadegr** [tobiaspfaff/grim_mouse#7]
year 1 after manny joins the resistance he cant walk through the open gate to the garage.
![screen shot 2014-02-26 at 10 17 21 pm](https://f.cloud.github.com/assets/6789829/2275248/eb51ee48-9f25-11e3-8d0e-723d6afc34ad.png)

only the keyboard works here.

**Comment by knellr** [comment]
Same here.

**Comment by tobiaspfaff** [comment]
Fixed in git

**Comment by tobiaspfaff** [comment]
Fixed in 0.3
