### ISSUE TITLE
cant climb on ladder 

### ISSUE THREAD

**Issue by nadegr** [tobiaspfaff/grim_mouse#8]
year 1 cant climb or interact with ladder.
![screen shot 2014-02-26 at 10 21 40 pm](https://f.cloud.github.com/assets/6789829/2275294/4d34cae0-9f26-11e3-871e-00a36831829b.png)

**Comment by tobiaspfaff** [comment]
Hmm...
a) does this happen immediately after you used the rope?
b) There is no hotspot for the ladder, but directly clicking on it (bottom part) should make Manny walk to it and climb. If that's confusing I might add a hotspot there.

**Comment by nadegr** [comment]
yes it happened immediately after using the rope. clicking on the middle part of the ladder didn't do anything. i think a hotspot would be helpful here. thanks!

**Comment by tobiaspfaff** [comment]
Fixed in git

**Comment by tobiaspfaff** [comment]
Fixed in 0.3
