### ISSUE TITLE
Non working hotspots

### ISSUE THREAD

**Issue by tobiaspfaff** [tobiaspfaff/grim_mouse#9]
- At rubacava circle crossroads
- Alley garage door (after escaping pridson)

-- reported by tomimt on adventuregamers

**Comment by Gonkalbell** [comment]
for me the alley garage door hotspots didn't even appear. There were also no hotspots in Maximino's office (And the hotspot to get into his office also led somewhere else), and parts of the ship during the very beginning of year 3.

**Comment by tobiaspfaff** [comment]
Rubacava, alley door and Maximo's office are fixed in git.

Gonkabell: where exactly are the hotspots missing in the ship?

**Comment by KaiFrederking** [comment]
I think Toto is missing a hotspot when he's on the phone and Manny wants to give him the anchor motif to get at Lola's photograph. Works manually, though.

**Comment by KaiFrederking** [comment]
Year 3: At Chepito, on the way to the pearl, I found it impossible to get his lamp after first exhausting all conversation options (and taking one round trip with him).
The only way to proceed was to load a previous game and grab the lamp during the conversation.

**Comment by KaiFrederking** [comment]
Another minor one: Year 3, beach at the far side of the crane. After pulling up the ship, the exit-hotspot to the beach where the ship lies does not work, since the scoop blocks the direct way. Manually leaving the scene works.

**Comment by KaiFrederking** [comment]
Year 4, Room with dying Glottis and little mechanic demons: When downstairs, near the oil barrel, double clicking the exit hotspot actually lets Manny go into the kitchen, not outside.

**Comment by tobiaspfaff** [comment]
KaiFrederking: Thanks for finding and reporting all these issues, that's a great help! If you find more, can you post them as separate issues; this makes it easier for me to keep track of what I already fixed.

**Comment by KaiFrederking** [comment]
One hotspot that works too well: When returning to the boobytrapped bone waggon, clicking on the dynamite will actually make Manny go there and defuse it, skipping the entire "defuse the trap" part.

**Comment by KaiFrederking** [comment]
It's the least I can do in return for your great work! I'll keep things separate from now on.

I have a pretty good idea how much brain and work you've already invested in this task - my sincere respect.

Date: Fri, 7 Mar 2014 11:22:54 -0800

**Comment by tobiaspfaff** [comment]
Ok, I split KaiFrederking's reports off into the new issues #19-#23. The year3 bug mentioned by Gonkalbell is very likely the same as #15, so I'm closing this bug.
